#!/usr/bin/env bash
set -euo pipefail

print_usage() {
  echo "Usage: $0 [-q] [-p] [-h]"
  echo ""
  echo "  $0 -m <make instructions>"
  echo "  $0 -p       --> cleans up"
  echo "  $0 -r       --> cleans up and reinstalls"
  echo ""
}

root_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
script_dir="${root_dir}/lib"
current_dir=$(pwd)

only_problems="0"
purge="0"
reset="0"
make_opts=""

. "${script_dir}/print"
. "${script_dir}/system"

no_opts="1"
while getopts "m:hqrp" o; do
  case "$o" in
    h) print_usage; exit 0;;
    q) only_problems="1";;
    p) purge="1";;
    r) reset="1"; purge=1;;
    m) make_opts=$OPTARG;;
  esac
  no_opts="0"
done

if [ "${no_opts}" = "1" ]; then
  print_usage; exit 1
fi

. "${script_dir}/utils"
if [[ "${purge}" == "1" ]]; then
  cleanup
else
  build
fi

if [[ "${reset}" == "1" ]]; then
  build
fi
